### ISSUE TITLE
Error when trying to match user accounts

### ISSUE THREAD

**Issue by ZaLiTHkA** [oasiswork/redmine-gitlab-migrator#5]
Greetings..

I'm in the process of migrating the issue tracking system for a small R&D team from Redmine to GitLab, found this migration script a couple days back, but I only got to try it out properly today. Please could someone help me work out what's going wrong here?

Quick environment overview for reference:

* Local Redmine 2.6.6 (local server), running at `http://redmine.nortechza.net`
* Hosted GitLab 8.9 (not my server), running at `https://gitlab.com`
* Running this script from inside a Linuxmint VM in VirtualBox with "Bridged Networking" (I am behind a proxy, but it is configured and working perfectly for desktop apps and `apt-get` commands)

At first my Redmine username (login) was `agreeff`, while my GitLab username (as seen in the URL `gitlab.com/u/<username>`) is `AndreGreeff`. Since I maintain my own Redmine instance, I manually edited my username in the DB directly to match my GitLab account. Unfortunately I still receive the same error. The GitLab project is private, so you won't be able to see anything at the URLs listed below.

As for the projects themselves, I created brand new dummy projects on both sides and added 3 versions and 3 issues to my dummy Redmine project specifically for testing this.

One the console I see:

```
andre@mint-dev1 ~/redmine-gitlab-migrator $ migrate-rg issues --redmine-key <xxx> --gitlab-key <xxx> http://redmine.nortechza.net/projects/dummy-project https://gitlab.com/nortech-sandbox/dummy-project --check
INFO: Project users are: AndreGreeff 
ERROR: Required users presence... FAILED
```

Before editing my Redmine username, the `INFO` line showed the name `agreeff`, so I know my change did take effect.

I wasn't sure which token to use from GitLab's side, so I tried with both the "Private Token" under the "Account" tab and with creating a new token under the "Personal Access Tokens" tab, but I get the exact same behaviour either way.

Am I missing something here..? Any ideas of what I could check / try? Is it possible to run this with debug output to see what the script is doing at each internal step?

**Comment by ZaLiTHkA** [comment]
Not sure if this helps at all, but if I try the exact same process running GitLab (`bitnami-gitlab-8.8.3-0` VM) in a local VM, I get the following error instead:

```
andre@mint-dev1 ~/redmine-gitlab-migrator $ migrate-rg issues --redmine-key <xxx> --gitlab-key <xxx> http://redmine.nortechza.net/projects/dummy-project http://10.66.9.120/test-group/dummy-project --check
INFO: Project users are: AndreGreeff 
INFO: Required users presence... OK
Traceback (most recent call last):
  File "/usr/local/bin/migrate-rg", line 9, in <module>
    load_entry_point('redmine-gitlab-migrator==1.0.2', 'console_scripts', 'migrate-rg')()
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 237, in main
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 119, in perform_migrate_issues
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 72, in check
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/commands.py", line 90, in check_no_issue
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/gitlab.py", line 109, in get_issues
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/gitlab.py", line 16, in get
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/__init__.py", line 37, in get
  File "/usr/local/lib/python3.4/dist-packages/redmine_gitlab_migrator-1.0.2-py3.4.egg/redmine_gitlab_migrator/__init__.py", line 31, in _req
  File "/usr/lib/python3/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
```

Tried this twice, once with `dummy-project` under my user namespace, and once with it under the `test-group` as seen above.

My user account on both GitLab.com and my local instance are named exactly the same way, just running a slightly different GitLab version.

For the record, I am now actually going through the script files from the above stacktrace to try work out more about this issue. But I'm not very familiar with Python, so I'm at quite a disadvantage right from the start.

**Comment by JocelynDelalande** [comment]
@ZaLiTHkA That's a fact that this script has been made for and tested only with a self-hosted gitlab instance.

> Basically, the fact that my username is not in the first 100 entries means this script can't find a match. I'll play around with changing this call to /api/v3/user?search=<name> instead. If this can't be used to search for multiple users simultaneously, I'll have to make a call for each Redmine user the script needs to link.

Yes, on big shared servers (like gitlab.com), listing all users is not an option, so you are left with issuing a request for each user. That changes a bit the script logic but would do the job.

Will be happy to integrate a proper patch implementing this idea (even if there is little chance that I can actually test it myself).

Good luck

Jocelyn

**Comment by ZaLiTHkA** [comment]
That does make sense, thanks for the clarification.

To be fair, I'm very much a noob with Python, but I understand enough to follow the syntax and I got some assistance from a few friends this morning with regards to implementing this idea.. My end goal here is as much a requirement for our development tools where I work as it is an educational experience for me as an individual.

Since this does indeed seem to be a pretty simple logic change, I'm very keen to see if I can make these changes myself first.. So if I get it working on my side I'll fork this repo and open a PR. :)

**Comment by ZaLiTHkA** [comment]
Ok, I think I'm in a bit over my head here.. Here's a quick diff of my changes so far:

```diff
diff --git a/redmine_gitlab_migrator/gitlab.py b/redmine_gitlab_migrator/gitlab.py
index 579863f..3354569 100644
--- a/redmine_gitlab_migrator/gitlab.py
+++ b/redmine_gitlab_migrator/gitlab.py
@@ -27,8 +27,9 @@ class GitlabInstance:
         self.url = url.strip('/')  # normalize URL
         self.api = client
 
-    def get_all_users(self):
-        return self.api.get('{}/users'.format(self.url))
+    def get_user(self, username):
+        get_user_url = '{}/users?username=' + username
+        return self.api.get(get_user_url.format(self.url))
 
     def get_users_index(self):
         """ Returns dict index of users (by login)
@@ -38,8 +39,13 @@ class GitlabInstance:
     def check_users_exist(self, usernames):
         """ Returns True if all users exist
         """
-        gitlab_user_names = set([i['username'] for i in self.get_all_users()])
-        return all((i in gitlab_user_names for i in usernames))
+        for i in usernames:
+            log.debug('looking for user ' + i + ' in GitLab...')
+            if len(self.get_user(username)) == 0:
+                log.debug('aww.. user not found.')
+                return False
+            log.debug('yay! user found!')
+        return True
 
 
 class GitlabProject(Project):
```

Problem is, I can't even tell whether or not I'm heading in the right direction here, because the `gitlab_users_index = gitlab_instance.get_users_index()` line in `commands.py@110` is a method which still relies on the `get_all_users` method, which is precisely what I'm trying to replace..

@JocelynDelalande, do you have any suggestions on how I could get around this...?

**Comment by ZaLiTHkA** [comment]
Over the weekend I pulled most of the changes made in this repo's forks (temporarily excluding my changes), seeing improvements such as including wiki pages and supporting pagination in the API data calls. Unfortunately I think I might have broken something else in the process though, because I still get errors with the `get_users_index` method.

Either way, this task is a little bit too urgent for me to waste too much time trying to learn Python well enough to get this to work, so I will stick to what I know and make a NodeJS powered migration tool instead.

Since I would still like to get a better understanding of Python, I'll come back to my fork of the project later when I have some extra time, but for now I say this issue can safely be abandoned. Feel free to reopen this if somebody else wants to take over.
